disabled_rules:
  - colon
  - comma
  - control_statement
  - trailing_whitespace
opt_in_rules:
  - empty_count
included:
  - Doolda
excluded:
  - Carthage
  - Pods
analyzer_rules:
  - explicit_self
force_cast: warning
force_try:
  severity: warning
line_length:
  warning: 145
  ignores_interpolated_strings: true
  ignores_urls: true
type_body_length:
  - 300
  - 400
file_length:
  warning: 1000
  error: 1200
type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"
